name: Build

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "./"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Run Lint
        run: yarn lint

      - name: Build
        run: yarn build
